### ISSUE TITLE
Install-ChocolateyFont cannot change execution policy

### ISSUE THREAD

**Issue by AnthonyMastrean** [bcurran3/ChocolateyPackages_CCR#70] opened 2019-02-04 18:21 UTC
I'm trying to use `Install-ChocolateyFont` in a package and I get the following error:

```
PS> choco install -y dejavufonts
...
ERROR: Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of Unrestricted. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
The install of dejavufonts was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\dejavufonts\tools\chocolateyInstall.ps1'.
 See log for details.
```

My execution policy settings are:

```
PS> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy    Unrestricted
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine    Unrestricted
```

The nuspec dep looks like this:

```xml
    <dependencies>
        <dependency id="chocolatey-font-helpers.extension" version="0.0.1" />
    </dependencies>
```

**Comment by bcurran3** [comment] 2019-02-04 18:50
Hi Anthony,

Swamped at the moment and don't have time to think this through or do any research.

Just checked my EP and LocalMachine is set to Bypass.

**Comment by AnthonyMastrean** [comment] 2019-02-04 18:57
No problem! We just had a baby, so I'm only updating packages when she naps 😅 . Just wanted to get the error written down. I was working on a similar Fonts extension, but they pointed me at yours. If I get time, I'll investigate from here.

**Comment by bcurran3** [comment] 2019-02-04 19:17
Congrats on the baby! (She your first? 2nd? 3rd? Etc?)

If you send me your install script I'll take a look at it, but I'm guessing it's good.

Looks like something is interfering with  "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass" in Install-ChocolateyFont.ps1 upstream but I don't know why. Maybe this statement needs to be changed for the better and you can help. (I thought it worked under all situations, I guess I could be wrong!)

Not that everybody should have LocalMachine set to Bypass, but try setting yours temporarily that way and see what happens.

In a day or two I'll have time to test and investigate properly.

**Comment by bcurran3** [comment] 2019-02-04 19:19
OFF SUBJECT: p.s. since you're updating packages.... make sure you're using this: 
https://chocolatey.org/packages/choco-nuspec-checker !!!!!

**Comment by bcurran3** [comment] 2019-02-05 03:12
Just did a little testing on my dev test machines.

On my basically virgin Server 2012 R2:
![image](https://user-images.githubusercontent.com/14026600/52250907-00d72b80-28af-11e9-8b82-82bbccddb5fd.png)
appears to be default and 
choco install font-awesome-font
installed without a hitch.

On my basically virgin Win10:
![image](https://user-images.githubusercontent.com/14026600/52250940-31b76080-28af-11e9-94ca-4fa57071b02a.png)
appears to be default and 
choco install font-awesome-font
installed without a hitch.

I then tried to duplicate your settings on the Win10 VM and got told NO!:
![image](https://user-images.githubusercontent.com/14026600/52251075-e0f43780-28af-11e9-8888-dc01892d52da.png)

From that I'm guessing the problem is a conflict with your Group Policy enforced execution policy settings.

Out of curiosity, do you have the same problem installing other fonts using my Chocolatey extension? What happens when you do choco install font-awesome-font, same thing? 

If you're not already using it, you can install https://chocolatey.org/packages/chocolateypowershell and do some testing easier inside of it.

You might also want to test inside of a non-domain joined VM to test your script and see how it goes. I'd like to find the full solution to what's going on here and if my extension can be made better, but this problem also might only effect a small amount of the Chocolatey Community based on a guess that the normal demographic isn't going to be on an AD domain and locked down.

**Comment by AnthonyMastrean** [comment] 2019-02-05 09:50
I’m curious why your function needs to override the process’s execution policy at all. I thought Chocolatey would already be managing that, as the executing process? (OK, I guess it’s really the current shell, but I’m calling choco 1st).

**Comment by bcurran3** [comment] 2019-02-06 22:02
From what I remember, I couldn't call Add-Font.ps1 or Remove-Font.ps1 without doing it. I'd get an error when running Install-ChocolateyFont and Uninstall-ChocolateyFont. Can't remember the details but it must have been related to the execution policy.

THEORETICALLY I might be able to load Add-Font.ps1 and Remove-Font.ps1 in the PSM1 and then not need to change/set the EP. Then possibly just alias Install-ChocolateyFont and Uninstall-ChocolateyFont to them and get rid of those scripts.

I'l do some testing when I have time.

**Comment by teknowledgist** [comment] 2019-08-30 15:06
I just submitted a fonthelp extension (because I didn't find this one -- doh!).  However, I based it on the same MS blog scripts you used, but totally overhauled it.  IMHO, those scripts were an mess!

I suspect my scripts get rid of this ExecutionPolicy problem because no outside scripts are run.  Since I spent the time, I hate to see it go to waste.  Would you like to look at what I did to maybe update (and simplify) your extension?

I can say the one piece that I was considering still poking at (and you may want to too) is the `$myFolder.GetDetailsOf($fileobj,21)` in the Add-Font.ps1 script.  That code, 21, is language dependent and will be different on non-english systems.  I'm not sure what the solution is for that.

[Edit] Just to be clear, I'm rescinding my extension submission.  Also, I too am using the `$myFolder.GetDetailsOf($fileobj,21)` line in my add-font code.

[Edit 2.0] I'll just be pushy.  Take'em:  😄 
[Add-Font.txt](https://github.com/bcurran3/ChocolateyPackages/files/3562623/Add-Font.txt)
[New-FontResourceType.txt](https://github.com/bcurran3/ChocolateyPackages/files/3562624/New-FontResourceType.txt)
[Remove-Font.txt](https://github.com/bcurran3/ChocolateyPackages/files/3562625/Remove-Font.txt)

**Comment by bcurran3** [comment] 2019-08-31 23:40
Sounds like yours might be better and I doubt I can improve on it. There's no reason why both can't exist. Let me know the package ID and I'll take a look at the full thing when I have time.

**Comment by teknowledgist** [comment] 2019-09-01 05:04
Gary pointed out that your extension already existed and suggested that there didn't need to be two extension packages that (aim to) do the same thing.  I agree with that, but since I wrote it to use it, you may as well see if you can utilize it to "tidy" your package up a bit so I can use that instead.

You can see [what I submitted here](https://chocolatey.org/packages/fonthelp.extension/1.0.0).  If you want to steal it all, I'm OK with that (even if you are making 💰 on it 😄).  If you want to make me a co-maintainer, that's fine too.  If you want to dump it on the digital scrap heap, I won't understand, but I won't complain either. (Although, I might push to get my package approved.) Your choice.  

As for the `GetDetailsOf()` method, [here is the best information I've been able to find on it](https://www.powershellmagazine.com/2015/04/13/pstip-use-shell-application-to-display-extended-file-attributes/).  Jaap says the `21` for the font name varies from Windows version and localization options.  The only way I can think of to get around that would be to:

1. identify a common font file that exists on every version and has the same font name on every version.
2. write another (internal) function for the package to copy that file to a folder outside the Fonts folder (this is because the `GetDetailsOf()` method does not appear to work within the Fonts folder).
3. Use something like Jaap's script to list all the metadata fields of that file and identify which number corresponds to the "Font Name" on that system.

That is really messy/ugly, so maybe that should be left to a future version?

**Comment by teknowledgist** [comment] 2019-09-03 02:38
The MS `add-font.ps1` script takes either a single font path or a folder and my `add-font` function takes only an array of font paths.  I can "fix" that pretty easily to allow an array of font paths or a folder path if you want.

Also, the MS scripts return 1 for any failure and 0 for full success.  My scripts identify how many fonts in the list (or folder) were successfully installed (and provides warnings for each failure).  Dependent font package maintainers might have to account for that change.

**Comment by teknowledgist** [comment] 2019-09-04 02:23
Sorry to be a PITA, but I'm sitting on a package (or two) until I can get a working font helper.  Would it be helpful if I submitted a PR that merges my work with your package?  I'm not looking for credit, just something that I can use.

**Comment by bcurran3** [comment] 2019-09-04 08:19
I understand you're very gung ho about this. 

I'm going to be honest, the extension was a simple one and done for me last year. Hell, I've mostly forgotten about it! :) There's a learning curve for me to understand the how's and why's of what you've done that I might not have the time for at the moment. I do want to understand the high level view of it as soon as possible though so I can figure out how to progress. 

I understand you took MS's scripts and modified them into something you feel is better. In basic terms, can you let me know what is better about them? Maybe more importantly why did they fail you or how does this extension using them not work for you? Let's start with that base. 

Assuming I jump on board, I'd say change the function names to match the current ones in my extension (Install-ChocolateyFont and Install-ChocolateyFont) for compatibility and I can add you as a package maintainer and then you can run with it.

SUMMARY: Convince me of the benefit (for the Chocolatey masses), then we can use your version as v0.0.2 of the extension as long as it's made backwards compatible.

If you want to talk mealtime about it, I can make myself available for chat online or on the phone.

**Comment by teknowledgist** [comment] 2019-09-05 03:04
I don't know that "modified" is the right word.  I borrowed the idea from those MS blog posted scripts and simplified (and, IMHO, improved) it.  

Comparing the MS scripts to mine:

1. The MS scripts total 1200+ lines, mine are ~225 but not dense/obscure.
2. The MS scripts have a lot of unused and unnecessary code in the type definition, mine is pared down to just what is used.
3. The MS scripts run all the subfunctions including creating a new type for each font, while mine processes reused bits only once.
4. The MS scripts don't use proper comment-based-help, mine do.
5. The MS scripts call write-host and send strings directly to the console, where mine rely on Write-Warning and Write-Verbose to be silent unless requested.
6. The information that is returned from the MS scripts on a -help switch is incorrect (indicating it can handle .pbf, .pfm and .mmm type fonts when the comments in the code specifically say it can't.
7. The MS `remove-font` script used a `-match` instead of `-eq` for the registry property (line 452) which could cause false positives.
8. The MS scripts have logical errors like when passing a folder containing a mix of font and non-font files.  It returns a single "1" (failed) or "0" (success) at the end, but passes back a message about non-fonts without using Write-Host, so any check for success/failure requires the dependent package maintainer to work with an array of strings.  Not difficult, but it's up to the dependent package maintainer to catch that subtlety of behavior.  My script does not (currently) accept folders, but I can easily add that option (and handle those errors properly).  

Comparing your current package to mine:

1. Your package relies on setting the execution policy to run a third-party script file that isn't part of the module where mine includes all functions int the module.
2. Requires the dependent package to track success (0) or failure (1) on a per-font basis or on an entire folder basis where mine could return how many fonts were successfully installed/uninstalled if an array is passed or report individually if the package maintainer passes them individually.

I'm not sure what to do about backwards compatibility due to my last point points (8 and 2).  Clearly, they are incompatible.  It would be weird to have the same misstep for folders, and I'm not sure I like a single pass/fail return for an entire folder (or array) full of font files since there could very well be some successes with a "fail" return.  My idea with the "successes" return was to lessen the burden on the package maintainer in deciding what a partial success meant.  Some fonts were (un)installed or non were.  With the individual returns, they have to think about whether to fail the package (and reset what may have already succeeded) or continue.  

I welcome your comments.  I'm truly not trying to be a burden on you either, so if I'm causing you indigestion, let me know and I'll flip on cancelling my originally submitted package and the repository will just have two, slightly-different font helper extensions.

**Comment by AnthonyMastrean** [comment] 2019-09-05 13:17
At this point, I think it makes sense to ask the Chocolatey team to take this extension, with @teknowledgist's changes, into [their repository](https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/extensions).

https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1324

**Comment by bcurran3** [comment] 2019-09-05 19:03
@AnthonyMastrean completely unnecessary and it's up to me if I want to give to coreteampackages or not, not you, not them.

@teknowledgist - man I admire your passion about this.

RE: Comparing the MS scripts to mine: 
- 1-3 impressive
- 4 moot as I don't see users interacting with it, just using the function from a package
- 5 subjective
- 6 same as # 4
-7 seems better but subjective since it's "could"
-8 this seems to be related to batch installing fonts, the intended use of the extension is for a Chocolatey installation script to install one font at a time.

RE: Comparing your current package to mine:
-1 good benefit. I've considered moving the MS scripts into the module and then aliasing the Chocolatey install/uninstall commands to run the MS functions. This should solve that problem and take care of @AnthonyMastrean - the sole person bumping into the problem and due to his corporate setup.
- 2 extension was intentionally created to install one font at a time - I purposely aimed for micromanagement and easy to use and read chocolateyinstall scripts.

Now all that might sound defensive, but I'm not really trying to be. I'm all for making it better and I think your changes have merit.

I only have two issues:
1 - design to install one font at a time
2 - that the changes are well tested

So I still propose that I add you as a maintainer. You design it to work one font at a time using existing install/uninstall commands to maintain backwards compatibility. Of course if the same commands can be used to install one font or a group of fonts that would be even better. Optionally there could be new commands Install-ChocolateyFonts and Uninstall-ChocolateyFonts. Then it could be pushed as v0.0.2-pre for group testing.

Thoughts?

**Comment by teknowledgist** [comment] 2019-09-05 20:45
I don't disagree with your "moot" and "subjective" comments.  Although I could have been more egalitarian with the language, I was attempting to provide objective comparisons, not listing bad/good qualities.  

Although some of the items are moot within the context of your intent with the extension, I do like to write scripts that are more readily adapted to other purposes.  Part of that, I feel, is using consistent and best-practices in coding style.  I certainly have deficiencies here as other than CompSci 101/102, I am self-taught.  I also think that if a feature is available, (like passing a folder) and not blocked at another level (like in your own scripts in the package), someone is going to try to use it despite any intent you may have.

I do like the new commands suggestion (or an optional `-multi` switch) as a solution to the incompatibilities.  I'll poke at that.

Let me see what I can cook up.

**Comment by teknowledgist** [comment] 2019-09-07 22:55
@bcurran3 I have updated the package on my end.  I added an optional `-multiple` switch so it works pretty much like your current extension (the console output is a little less "noisy" without a `-verbose`).  

* It works great with my `-multi` font testing.
* It works great for your "font-awesome-font".  
* I got the same result for the "crosextrafonts-carlito-font" with my v0.0.2 of the extension compared to your v0.0.1 which is to say the fonts didn't install. ("file not found" - I think because it assumes the current working directory.)  In both cases, Chocolatey -- not seeing an exception from the package -- happily continues on and claims the package successfully installed.

In investigating that last example I identified an actual problem with your package that should not be made backward compatible...

Your `Install-ChocolateyFont` function doesn't do anything with the exit code from the MS script, so  any dependent package code that calls `Install-ChocolateyFont` will *never* know of a failure without capturing and parsing `Write-Host` output.  The return of `Install-ChocolateyFont` is always 0 (success) even if the MS script passes an exit code of 1.

Thus, I propose a potentially breaking change:

* v0.0.1 outputs a `Write-Host` "xxx not found" message and returns 0 (always).
* v0.0.2 outputs a `write-warning` message (which would not be captured by a variable assigned to the call return) and returns 0 for single-font success, 1 for single-font failure, and the number of successes for `-multi` calls

#### Changes:
1. Existing packages that recognize the problem and are parsing the console output will break.
2. Existing packages (like font-awesome-font) that don't capture the function return will output a 0 or 1 to the console when they didn't before.  
3. Existing packages that are watching for non-zero error codes will now work.

**Comment by bcurran3** [comment] 2019-09-08 02:22
I just sent you a maintainer request for the package.

I haven't had a chance to test. Please push up with a -pre and I should be able to test Monday or Tuesday.

**Comment by teknowledgist** [comment] 2019-09-08 17:56
@bcurran3 Do you want me to push a PR or just submit from my own files?  I was assuming you wanted the site/source/etc. to point to your repo.

**Comment by bcurran3** [comment] 2019-09-08 22:13
You can just push. I can put it in mine later. No rush. You're the main man now with all the work you did. :)

**Comment by bcurran3** [comment] 2019-09-09 06:56
RE: https://chocolatey.org/packages/chocolatey-font-helpers.extension/0.0.2-pre

I just tested it six times with install and uninstall of (my) old font packages and it passed with flying colors. Failed once when I purposely had the font in use. :) 

Personal preference: On the return codes, I'd prefer not to see them; i.e. Out-Null if possible.

I'm good with it being finalized. Great job. Great for the community. Thanks!

**Closed as completed by bcurran3** 2019-09-09 06:56 UTC
Labels: Enhancement, Next_Package_Release, Done

**Comment by gep13** [comment] 2019-09-11 06:40
>@teknowledgist said...
Do you want me to push a PR or just submit from my own files? I was assuming you wanted the site/source/etc. to point to your repo.

Since the package source url of the package is still pointing to this repo, it would be good to get the source files updated to reflect what has been pushed to chocolatey.org, or to update the package source url to point to where they now reside.

**Comment by bcurran3** [comment] 2019-09-11 09:20
Done.
