### ISSUE TITLE
Please add options for the Java dependancy in the Angry IP Scanner Chocolatey package

### ISSUE THREAD

**Issue by ctminime** [bcurran3/ChocolateyPackages_CCR#161] opened 2020-05-14 21:24 UTC
Angry IP Scanner works just fine with AdoptOpenJDK 11 openj9 or Hotspot. Since Oracle Java is no longer free, these are much better alternatives.

I am sure any of these chocolatey packages would work:
openjdk8
openjdk11
adoptopenjdk11
adoptopenjdk11openj9
adoptopenjdk11jre
adoptopenjdk11openj9jre
adoptopenjdk8
adoptopenjdk8openj9
adoptopenjdk8jre
adoptopenjdk8openj9jre

I personally use AdoptOpenJDK11openj9 and I have no issues.

Using AdoptOpenJDK is supported by Angry IP but requires enabling "JavaSoft (Oracle) registry keys".

https://angryip.org/download/#windows

The real question is, which one should be default? In my personal opinion, it should definitely not be Oracle Java (javaruntime).

**Comment by TheCakeIsNaOH** [comment] 2020-05-16 22:54
Duplicate of #142

**Comment by ctminime** [comment] 2020-05-18 17:04
Whoops, sorry about the dupe. I thought I looked but apparently not.

**Comment by bcurran3** [comment] 2020-05-29 07:36
closing as dupe

**Closed as completed by bcurran3** 2020-05-29 07:36 UTC
Labels: Duplicate
