### ISSUE TITLE
need clean-up in C:\ProgramData\chocolatey\.chocolatey

### ISSUE THREAD

**Issue by enihcam** [bcurran3/ChocolateyPackages_CCR#302] opened 2022-06-13 13:57 UTC
need purge those folders for old versions in `C:\ProgramData\chocolatey\.chocolatey`

```
C:\ProgramData\chocolatey\.chocolatey>dir
 Volume in drive C has no label.
 Volume Serial Number is 5E93-49A5

 Directory of C:\ProgramData\chocolatey\.chocolatey

...
06/11/2022  02:45 AM    <DIR>          GoogleChrome.102.0.5005.115
06/09/2022  09:33 PM    <DIR>          GoogleChrome.102.0.5005.63
...
06/09/2022  10:04 PM    <DIR>          sumatrapdf.install.3.4.5
06/11/2022  02:46 AM    <DIR>          sumatrapdf.install.3.4.6
06/09/2022  11:24 PM    <DIR>          wechat.3.7.0.29
06/11/2022  02:47 AM    <DIR>          wechat.3.7.0.30
...
```

**Comment by bcurran3** [comment] 2022-07-25 01:29
This has been on the roadmap for a long time (years). It's actually in the package description, "Clean up C:\ProgramData\chocolatey\.chocolatey" and it might actually be in another GH issue. 

It's a high priority for when I have the time.

**Comment by bcurran3** [comment] 2022-07-31 05:47
Dupe of https://github.com/bcurran3/ChocolateyPackages/issues/124

Please feel free to update any comments or thoughts there.

**Closed as completed by bcurran3** 2022-07-31 05:47 UTC
Labels: Duplicate
