### ISSUE TITLE
choco-package-list-backup: Add support for backing up installArguments.

### ISSUE THREAD

**Issue by Corey-Keller** [bcurran3/ChocolateyPackages_CCR#168] opened 2020-06-22 21:20 UTC
[DecryptChocoArgs](https://github.com/CollinChaffin/DecryptChocoArgs) is one option that could be used to get the args for a given package. A LOT of my packages are in custom locations for example.

**Comment by bcurran3** [comment] 2020-06-25 15:01
This is a dupe of https://github.com/bcurran3/ChocolateyPackages/issues/7 AFAIK.

**Closed as completed by bcurran3** 2020-06-25 15:01 UTC
Labels: Duplicate
